In [5]:
import pandas as pd
from pathlib import Path
import json
import csv

In [3]:
speakers_df = pd.read_json("speakers.json", orient = "record")

In [4]:
display(speakers_df)

,u0,u2,u3,u4,u5,u11,u1,u9,u7,u6,...,u9025,u9026,u9027,u9032,u9030,u9029,u9033,u9028,u9031,u9034
meta,"{'character_name': 'BIANCA', 'movie_idx': 'm0'...","{'character_name': 'CAMERON', 'movie_idx': 'm0...","{'character_name': 'CHASTITY', 'movie_idx': 'm...","{'character_name': 'JOEY', 'movie_idx': 'm0', ...","{'character_name': 'KAT', 'movie_idx': 'm0', '...","{'character_name': 'WALTER', 'movie_idx': 'm0'...","{'character_name': 'BRUCE', 'movie_idx': 'm0',...","{'character_name': 'PATRICK', 'movie_idx': 'm0...","{'character_name': 'MICHAEL', 'movie_idx': 'm0...","{'character_name': 'MANDELLA', 'movie_idx': 'm...",...,"{'character_name': 'BLOOMFIELD', 'movie_idx': ...","{'character_name': 'BOY-PULLEN', 'movie_idx': ...","{'character_name': 'CHELMSFORD', 'movie_idx': ...","{'character_name': 'NORRIS-NEWMAN', 'movie_idx...","{'character_name': 'DURNFORD', 'movie_idx': 'm...","{'character_name': 'CREALOCK', 'movie_idx': 'm...","{'character_name': 'STUART SMITH', 'movie_idx'...","{'character_name': 'COGHILL', 'movie_idx': 'm6...","{'character_name': 'MELVILL', 'movie_idx': 'm6...","{'character_name': 'VEREKER', 'movie_idx': 'm6..."
vectors,[],[],[],[],[],[],[],[],[],[],...,[],[],[],[],[],[],[],[],[],[]

In [20]:
# read json
with open('speakers.json', encoding='utf-8') as f:
    speakers_data = json.loads(f.read())

# create dataframe
speakers_df = pd.json_normalize(speakers_data)

# save to csv
speakers_df.to_csv('speakers.csv', index=False, encoding='utf-8')

In [21]:
speakers_df_csv = pd.read_csv('speakers.csv')